### ISSUE TITLE
vulnerabilities in docker image

### ISSUE THREAD

**Issue by alexkutsan** [arugifa/standardnotes-web-docker#1]
During building docker container wound warning: 

```
Bundled gems are installed into `/usr/local/bundle`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):                              
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"a
ny"} (current: {"os":"linux","arch":"x64"})

audited 10757 packages in 6.82s
found 382 vulnerabilities (3 low, 1 moderate, 378 high)
  run `npm audit fix` to fix them, or `npm audit` for details                                                        
Running "haml:dist" (haml) task

```
I am not good in nodejs apps. Is it standartnotes issue?

**Comment by arugifa** [comment]
Hi @alexkutsan ,

Thanks for your feedback, and sorry for the late reply: I forgot to turn notifications ON for this repository.

I will have a look into that. But I guess the problem is related to the fact that I didn't update this image since a while :)

**Comment by arugifa** [comment]
As the author of Standard Notes published some time ago an image for the web UI, I would highly recommend to use it instead of mine though :) 

https://hub.docker.com/r/standardnotes/web
